/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz.alexac.leveleditor.ui;

import xyz.alexac.leveleditor.model.LevelElement;
import xyz.alexac.leveleditor.model.ProjectSettings;

/**
 *
 * @author alex-ac
 */
public class EditorWindow
        extends javax.swing.JFrame {
  private final EditorWindowDelegate delegate_;
  private final ProjectSettings settings_;
  private LevelElement element_;

  /**
   * Creates new form EditorWindow
   *
   * @param delegate
   */
  public EditorWindow(EditorWindowDelegate delegate, ProjectSettings settings) {
    delegate_ = delegate;
    settings_ = settings;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    buttonGroup1 = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jSpinner1 = new javax.swing.JSpinner();
    jLabel3 = new javax.swing.JLabel();
    jSpinner2 = new javax.swing.JSpinner();
    jLabel4 = new javax.swing.JLabel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jRadioButton2 = new javax.swing.JRadioButton();
    filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
    objectView1 = new xyz.alexac.leveleditor.ui.ObjectView();
    objectView1.setSettings(settings_);
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(800, 600));
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Grid Size");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.ipady = 15;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    getContentPane().add(jLabel1, gridBagConstraints);

    jLabel2.setText("Width:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.ipadx = 50;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
    getContentPane().add(jLabel2, gridBagConstraints);

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(256, 1, null, 1));
    jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        gridWidthChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.ipadx = 50;
    getContentPane().add(jSpinner1, gridBagConstraints);

    jLabel3.setText("Height:");
    jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.ipadx = 50;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 0);
    getContentPane().add(jLabel3, gridBagConstraints);

    jSpinner2.setModel(new javax.swing.SpinnerNumberModel(128, 1, null, 1));
    jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        gridHeightChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.ipadx = 50;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
    getContentPane().add(jSpinner2, gridBagConstraints);

    jLabel4.setText("Level Element");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    getContentPane().add(jLabel4, gridBagConstraints);

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setSelected(true);
    jRadioButton1.setText("2D tiles selection");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewModeChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    getContentPane().add(jRadioButton1, gridBagConstraints);

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("Occupied Voxels selection");
    jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewModeChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
    getContentPane().add(jRadioButton2, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridheight = 3;
    getContentPane().add(filler1, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(objectView1, gridBagConstraints);

    jMenu1.setText("File");

    jMenuItem1.setText("Open Object");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onOpenObject(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onOpenObject(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOpenObject
    delegate_.openObject();
  }//GEN-LAST:event_onOpenObject

  private void gridHeightChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gridHeightChanged
    settings_.setTileHeight(((Integer) (jSpinner2.getModel().getValue())));
  }//GEN-LAST:event_gridHeightChanged

  private void gridWidthChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gridWidthChanged
    settings_.setTileWidth(((Integer) (jSpinner1.getModel().getValue())));
  }//GEN-LAST:event_gridWidthChanged

  private void viewModeChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewModeChanged
    objectView1.setMode(
            jRadioButton1.isSelected()
                    ? ObjectView.MODE_GRID
                    : ObjectView.MODE_VOXEL);
  }//GEN-LAST:event_viewModeChanged

  public void setElement(LevelElement element) {
    element_ = element;
    objectView1.setElement(element);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.Box.Filler filler1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JSpinner jSpinner1;
  private javax.swing.JSpinner jSpinner2;
  private xyz.alexac.leveleditor.ui.ObjectView objectView1;
  // End of variables declaration//GEN-END:variables
}
