/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz.alexac.leveleditor.ui;

import xyz.alexac.leveleditor.model.DrawingLayer;
import xyz.alexac.leveleditor.model.ProjectSettings;

/**
 *
 * @author alex-ac
 */
public class ProjectSettingsView extends javax.swing.JPanel {
  private final ProjectSettings settings_;

  /**
   * Creates new form ProjectSettingsView
   */
  public ProjectSettingsView(ProjectSettings settings) {
    settings_ = settings;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jSpinner1 = new javax.swing.JSpinner();
    jLabel2 = new javax.swing.JLabel();
    jSpinner2 = new javax.swing.JSpinner();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

    setBorder(javax.swing.BorderFactory.createTitledBorder("Project Settings"));
    setMinimumSize(new java.awt.Dimension(300, 323));
    setPreferredSize(new java.awt.Dimension(200, 300));
    setLayout(new java.awt.GridBagLayout());

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grid Size"));
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Width:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jLabel1, gridBagConstraints);

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(256, 10, null, 1));
    jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        gridWidthChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jSpinner1, gridBagConstraints);
    jSpinner1.getModel().setValue(settings_.getTileWidth());

    jLabel2.setText("Height:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jLabel2, gridBagConstraints);

    jSpinner2.setModel(new javax.swing.SpinnerNumberModel(128, 16, null, 1));
    jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        gridHeightChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel1.add(jSpinner2, gridBagConstraints);
    jSpinner2.getModel().setValue(settings_.getTileHeight());

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.weighty = 0.1;
    add(jPanel1, gridBagConstraints);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Layers"));
    jPanel2.setMinimumSize(new java.awt.Dimension(100, 109));
    jPanel2.setLayout(new java.awt.GridBagLayout());

    jList1.setModel(new LayerListModel(settings_));
    jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jList1.setCellRenderer(new LayerListCellRenderer());
    jScrollPane1.setViewportView(jList1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    jPanel2.add(jScrollPane1, gridBagConstraints);

    jButton1.setText("Add");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addLayer(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    jPanel2.add(jButton1, gridBagConstraints);

    jButton2.setText("Delete");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteLayer(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    jPanel2.add(jButton2, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.1;
    jPanel2.add(filler2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 0.1;
    gridBagConstraints.weighty = 0.1;
    add(jPanel2, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void addLayer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLayer
    // TODO add your handling code here:
    settings_.addLayer(new DrawingLayer());
  }//GEN-LAST:event_addLayer

  private void deleteLayer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLayer
    // TODO add your handling code here:
    if (jList1.isSelectionEmpty()) {
      return;
    }
    settings_.removeLayer(jList1.getSelectedValue());
  }//GEN-LAST:event_deleteLayer

  private void gridWidthChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gridWidthChanged
    // TODO add your handling code here:
    settings_.setTileWidth((Integer) jSpinner1.getModel().getValue());
  }//GEN-LAST:event_gridWidthChanged

  private void gridHeightChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gridHeightChanged
    // TODO add your handling code here:
    settings_.setTileHeight((Integer) jSpinner2.getModel().getValue());
  }//GEN-LAST:event_gridHeightChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.Box.Filler filler2;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JList<DrawingLayer> jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSpinner jSpinner1;
  private javax.swing.JSpinner jSpinner2;
  // End of variables declaration//GEN-END:variables
}
